"component: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
"component: cli":
  - changed-files:
      - any-glob-to-any-file:
          - cli/**/*
"component: documentation-website":
  - changed-files:
      - any-glob-to-any-file:
          - documentation-website/**/*
"component: examples":
  - changed-files:
      - any-glob-to-any-file:
          - examples/**/*
"component: framework":
  - changed-files:
      - any-glob-to-any-file:
          - framework/**/*
"component: history-microservice":
  - changed-files:
      - any-glob-to-any-file:
          - history-microservice/**/*
"component: history-website":
  - changed-files:
      - any-glob-to-any-file:
          - history-website/**/*
"component: translation":
  - changed-files:
      - any-glob-to-any-file:
          - '*/language/*.yml'
"component: mindmap":
  - changed-files:
      - any-glob-to-any-file:
          - mindmap/**/*
"component: tooling":
  - changed-files:
      - any-glob-to-any-file:
          - tools/**/*
          - "*/tools/**/*"
"component: continuous-integration":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/*"
"component: desktop":
  - changed-files:
      - any-glob-to-any-file:
          - desktop/**/*
